# Generated by Django 4.1.2 on 2022-12-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_myorder_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyOrder',
        ),
    ]
